site_name: VergeOS Docs
site_url: https://docs.verge.io/
repo_url: https://github.com/verge-io/docs
repo_name: verge-io/docs
edit_uri: edit/develop/docs/


theme:
  name: material
  custom_dir: overrides
  logo: assets/vergelogomark.svg
  favicon: assets/vergelogomark.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - blog:
      blog_dir: kb
      post_url_format: "{slug}"
      blog_toc: true
      archive: false
  - search:
      prebuild_index: true
      lang:
      - en
  - glightbox
markdown_extensions:
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 2
#extra:
#  consent:
#    title: Cookie consent
#    description: >- 
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
#  - material.extensions.preview:
#      targets:
#        include:
#          - glossary.md      

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VergeIO_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/verge-io/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnFu28s0GBVi18j7Ez3MXRg
  generator: false
copyright: |
  &copy; 2024 <a href="https://verge.io" target="_blank" rel="noopener"> Verge.io</a>

nav:
  - Home:
    - Welcome: index.md
  - Implementation Guide:
    - Introduction: implementation-guide/concepts.md
    - Sizing: implementation-guide/sizing.md
    - VergeOS Pre-Installation: implementation-guide/pre-installation.md
    - VergeOS Installation:
      - Bootable Media: implementation-guide/install-media.md
      - Installation: implementation-guide/installation-guide.md
      - Scale Out Nodes: implementation-guide/scale-out-nodes.md
      - Compute Nodes: implementation-guide/compute-nodes.md
      - Storage Nodes: implementation-guide/storage-nodes.md
    - VergeOS Post-Installation: implementation-guide/post-installation.md
  - Reference Architecture:
    - Edge / ROBO: reference-architecture/edge.md
    - Cloud Providers: reference-architecture/csp.md
    - Life / Data Science: reference-architecture/data-science.md
    - VMware Backup: reference-architecture/vmware-backup.md
  - Knowledge Base:
    - kb/index.md
  - Product Guide:
    - VergeIO User Interface: ProductGuide/UI-Overview.md
    - Configuration:
      - Authentication:
        - Authorization Sources: ProductGuide/AuthSources-General.md
        - Azure AD: ProductGuide/AzureADAuth.md
        - Google: ProductGuide/GoogleAuth.md
      - Two Factor Authentication: ProductGuide/2factorEmailAuth.md
      - Certificates: ProductGuide/certificates.md
      - GPU:
        - Passthrough: ProductGuide/GPUPassthrough.md
        - NVIDIA vGPU: ProductGuide/nvidiavGPU.md
        - Tenant GPU: ProductGuide/gpu-sharetenant.md
      - IPMI:
        - IPMI: ProductGuide/IPMI.md
        - System Event Log (SEL): ProductGuide/SEL
      - Tenants:
        - Creating Tenants: ProductGuide/createtenants.md
        - Increasing Resources: ProductGuide/tenantsaddresources.md
        - Reducing Resources: ProductGuide/reducetenantresources.md
        - Assigning External IP Addresses: ProductGuide/assignIPtotenant.md
        - Sharing Files: ProductGuide/providefilestotenant.md
        - Snapshots: ProductGuide/tenantsnapshots.md
    - Permissions:
      - Users and Groups: ProductGuide/usersgroups.md
      - Permissions: ProductGuide/permissions.md
    - Maintenance & Monitoring:
      - Drive Replacement: ProductGuide/DriveReplacement.md
      - Maintenance Mode: ProductGuide/maintenancemode.md
      - Sites Dashboard:
        - Overview: ProductGuide/sitesoverview.md
        - Adding Sites: ProductGuide/configuringsitesdash-addingsites.md
      - Subscriptions:
        - Overview: ProductGuide/subscriptions-overview.md
        - Profiles: ProductGuide/subscriptionprofiles.md
      - Tasks / Events:
        - Create Automated Tasks: ProductGuide/createtasks.md
      - Updates:
        - Applying Updates: ProductGuide/runningupdates.md
        - Settings: ProductGuide/updatesettings.md
    - NAS:
      - Overview:
        - NAS Service: ProductGuide/NASservice
      - Configuration:
        - Local Volumes: ProductGuide/naslocalvolumes.md
        - Remote Volumes: ProductGuide/nasremotevolumes.md
        - Shares: ProductGuide/nasshares.md
        - VM Export: ProductGuide/vmexportvolume.md
        - Volume Syncs: ProductGuide/volumesyncs.md
    - Networking:
      - Quick Start: 
        - Overview: ProductGuide/networkoverview.md
        - Connect to an Existing LAN/WAN: ProductGuide/connectLANWAN.md
        - Create an Internal Network with External Access: ProductGuide/internalwithextaccess.md
        - Creating an Internal Layer2 Network: ProductGuide/internal-layer2.md
        - Create a Layer 3 Internal Network: ProductGuide/internal-layer3.md
        - Create a DHCP Static Entry: ProductGuide/dhcpstaticlease.md
        - Assign an External IP to an Internal network: ProductGuide/assignexternalIP.md
        - Create a 1:1 NAT: ProductGuide/NAT1to1.md
      - Configuration:
        - Creating an Internal Network: ProductGuide/internalnetworks.md
        - Using Aliases: ProductGuide/aliases.md
        - Network Rules: ProductGuide/networkrules.md
      - Monitoring:
        - Tracking Network Statistics: ProductGuide/trackingnetstats.md
        - Port Mirroring: ProductGuide/portmirroring.md
        - Network Diagnostics Tool: ProductGuide/netdiagnostics.md
      - VPN:
        - Overview: ProductGuide/VPNoverview.md
        - IPSec: ProductGuide/IPSEC.md
        - WireGuard: ProductGuide/wireguardconfig.md
        - WireGuard Examples: ProductGuide/wireguard-examples.md
      - Troubleshooting:
        - Network Troubleshooting: ProductGuide/net-troubleshooting.md
    - DR & Backup:
      - Site Syncs:
        - Configuration: ProductGuide/sync-configuration.md
        - Monitoring: ProductGuide/monitoringsitesyncs.md
        - Sync Back: ProductGuide/syncingback.md
        - Manual Sync: ProductGuide/manualsitesyncs.md
        - Repair Server: ProductGuide/repairserver.md
      - Snapshots:
        - Overview: ProductGuide/snapshots-overview.md
        - Profiles: ProductGuide/snapshot-profiles.md
        - VM Snapshots and Restore: ProductGuide/VMsnapshotsandrestores.md
        - Tenant Snapshots: ProductGuide/tenantsnapshots.md
        - Cloud Snapshots and Restore: ProductGuide/cloudsnapshotandrestore.md
        - NAS Snapshots and Restore: ProductGuide/volumesnapsandrestores.md
    - Virtual Machines:
      - Quick Start:
        - Best Practices: ProductGuide/VMbestpractices.md
        - Creating Virtual Machines: ProductGuide/creatingvms.md
        - Virtual Machine Drives: ProductGuide/VMdrives.md
        - Virtual Machine Network Interfaces: ProductGuide/VMNics.md
        - Virtual Machine Fields: ProductGuide/VMfielddescriptions.md
        - VM Guest Agent: ProductGuide/VMguestagent.md
      - Importing VMs: 
        - From Media Images: ProductGuide/importfromupload.md
        - From VMware Backup: ProductGuide/importvmware.md
        - From NAS Volume: ProductGuide/importfromNAS.md
        - Viewing Import Jobs: ProductGuide/viewimportjobs.md
      - VDI:
        - Instructions for the Administrator: ProductGuide/VDI-Administrator.md
        - Instructions for the User: ProductGuide/VDI-User.md
        - Virtual Machine Remote Console: ProductGuide/VM-RemoteConsole.md
    - VSAN:
      - Overview:
        - Storage Tiers: ProductGuide/storagetiers.md
        - Uploading to the vSAN: ProductGuide/uploadingtovSAN.md
        - Preferred Tier: ProductGuide/preferredtiers.md
        - Removing ISO Files with References: ProductGuide/removing-isorefs.md
  - Glossary: glossary.md

#build