site_name: VergeOS Docs
site_url: https://docs.verge.io/
repo_url: https://github.com/verge-io/docs
repo_name: verge-io/docs
edit_uri: edit/develop/docs/


theme:
  name: material
  custom_dir: overrides
  logo: assets/vergelogomark.svg
  favicon: assets/vergelogomark.svg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - announce.dismiss
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - blog:
      blog_dir: kb
      post_url_format: "{slug}"
      blog_toc: true
      archive: false
  - search:
      prebuild_index: true
      lang:
      - en
  - glightbox
markdown_extensions:
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
      toc_depth: 2
#extra:
#  consent:
#    title: Cookie consent
#    description: >- 
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
#  - material.extensions.preview:
#      targets:
#        include:
#          - glossary.md      

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VergeIO_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/verge-io/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnFu28s0GBVi18j7Ez3MXRg
  generator: false
copyright: |
  &copy; 2024 <a href="https://verge.io" target="_blank" rel="noopener"> Verge.io</a>

nav:
  - Home:
    - Welcome: index.md
#  - Writing Guide:
#    - Writing Guide: how-to-write-a-verge-guide.md
  - Implementation Guide:
    - Introduction: implementation-guide/introduction.md
    - Core Concepts: implementation-guide/concepts.md
    - Sizing: implementation-guide/sizing.md
    - Reference Architecture:
      - Network Design: implementation-guide/network-design.md
      - Edge / ROBO: implementation-guide/edge.md
      - SMB : implementation-guide/smb.md
      - Cloud Providers: implementation-guide/csp.md
      #- Enterprise: implementation-guide/enterprise.md
      - Life / Data Science: implementation-guide/data-sciense.md
      - VMware Backup: implementation-guide/vmware-backup.md
      #- Education: implementation-guide/edu.md
#      - Memory / RAM Considerations: implementation-guide/ram-design.md
    - Pre-Installation: 
#      - Key Terms / Glossary: implementation-guide/pre-installation.md
      - Checklist: implementation-guide/pre-install-checklist.md
      - Bootable Media: implementation-guide/install-media.md
    - vergeOS Installation:
      - Installation: implementation-guide/installation-guide.md
      - Scale Out Nodes: implementation-guide/scale-out-nodes.md
      - Compute Nodes: implementation-guide/compute-nodes.md
      - Storage Nodes: implementation-guide/storage-nodes.md
    - vergeOS Post Installation:
      - vSAN: implementation-guide/vsan.md
      - SSL: implementation-guide/ssl.md
      - Tenants: implementation-guide/tenant.md
  - Knowledge Base:
    - kb/index.md      
  - Glossary: glossary.md

  