site_name: Documentation
site_url: https://docs.verge.io/
repo_url: https://github.com/vergedocs/docs
repo_name: vergedocs/docs
edit_uri: edit/develop/docs/


theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - glightbox
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VergeIO_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/verge-io/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnFu28s0GBVi18j7Ez3MXRg
copyright: |
  &copy; 2021 <a href="https://verge.io" target="_blank" rel="noopener"> Verge.io</a>

nav:
  - Home:
    - Welcome: index.md
  - Implementation Guide:
    - Introduction: implementation-guide/introduction.md
    - Design Architechtures:
      - Key Terms / Glossary: implementation-guide/glossary.md
      - Basic Cluster Design: implementation-guide/basic-cluster-design.md
      - Advanced Cluster Design: implementation-guide/advanced-cluster-design.md
      - Network Design: implementation-guide/network-design.md
      - Memory / RAM Considerations: implementation-guide/ram-design.md
    - Pre-Installation: 
      - Key Terms / Glossary: implementation-guide/pre-installation.md
      - Checklist: implementation-guide/pre-install-checklist.md
