site_name: Documentation
site_url: https://docs.verge.io/
repo_url: https://github.com/vergedocs/docs
repo_name: vergedocs/docs
edit_uri: edit/develop/docs/


theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo-noname.png
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins:
  - glightbox
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VergeIO_Inc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/verge-io/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnFu28s0GBVi18j7Ez3MXRg
copyright: |
  &copy; 2021 <a href="https://verge.io" target="_blank" rel="noopener"> Verge.io</a>

nav:
  - Home:
    - Welcome: index.md
  - Implementation Guide:
    - Introduction: implementation-guide/introduction.md
    - Design Architechtures:
      - Key Terms / Glossary: implementation-guide/glossary.md
      - Basic Cluster Design: implementation-guide/basic-cluster-design.md
      - Advanced Cluster Design: implementation-guide/advanced-cluster-design.md
      - Network Design: implementation-guide/network-design.md
      - Memory / RAM Considerations: implementation-guide/ram-design.md
    - Pre-Installation: 
      - Key Terms / Glossary: implementation-guide/pre-installation.md
      - Checklist: implementation-guide/pre-install-checklist.md
      - Bootable Media: implementation-guide/install-media.md
    - vergeOS Installtion:
      - Key Terms / Glossary: implementation-guide/installation.md
      - Installation: implementation-guide/installation-guide.md
  - Knowledge Base:
    - Trim: kb/trim.md
    - API Tables: kb/API-Tables.md
    - Allow Root to Tenant Site: kb/AllowRootToTenantSite.md
    - DiskDiscard: kb/Disk-Discard.md
    - Import VM from Media: kb/Importing-VMs-from-Media.md
    - Accessing the User Interface from an Internal Network: kb/access-ui-from-internal.md
    - Accessing the User Interface from a VM: kb/accessing-ui-from-a-vm.md
    - Add Media to Tenant: kb/add-media-to-tenants.md
    - Add a vlan: kb/adding-a-vlan.md
#    kb/adding-resources.md
#    kb/adding-storage.md
#    kb/api.md
#    kb/best-practices-pfsense-firewall.md
#    kb/bootable-usb.md
#    kb/branding.md
#    kb/change-resolution-on-uefi.md
#    kb/configuring-ipsec.md
#    kb/configuring-vm-export.md
#    kb/db-best-practices.md
#    kb/exporting-a-vm.md
#    kb/generating-system-diags.md
#    kb/identifying-a-failed-disk.md
#    kb/importing-p2v-or-v2v.md
#    kb/importwindowsserveruefi.md
#    kb/increase-max-ram.md
#    kb/isolate-a-vm.md
#    kb/loading-virtio-drivers-in-windowsrc.md
#    kb/managing-media-images.md
#    kb/network-blocks.md
#    kb/non-persistent-vm.md
#    kb/preferred-tier-usage.md
#    kb/preinstall-checklist.md
#    kb/proper-power-sequence.md
#    kb/proxy.md
#    kb/recover-single-vm-from-cloud-snapshot.md
#    kb/reset-tenant-admin-password.md
#    kb/resizing-a-virtual-disk-drive.md
#    kb/reviewing-system-logs.md
#    kb/routing-internal-networks.md
#    kb/scaling-up-a-vsan.md
#    kb/share-vm-into-tenant.md
#    kb/snapshot-sync-errors.md
#    kb/tenant-statistics.md
#    kb/trim.md
#    kb/troubleshootingnas.md
#    kb/uefi-tweaks-for-imported-vms.md
#    kb/understanding-traffic-flow.md
#    kb/unexpected-vsan-growth.md
#    kb/vergeio-update-instructions.md
#    kb/virtual-wires.md
#    kb/vm-network-connectivity-issues.md
#    kb/vmware-backup-dr-guide.md
#    kb/vsan-encryption.md
#    kb/win11-bypass-tpm.md
#    kb/windows-disks-offline-after-restart.md
#    kb/windows-restored-vm-not-bootable.md
#    kb/windows-slow-format.md
#    kb/windows-time-shift.md
#    kb/windows-unable-to-detect-drive.md
#    kb/windows-unexpected-restart.md
#    kb/wireguard-nameservers.md
#    kb/wireguard-setup-remote-access-vpn.md
#    kb/workloads-failing-to-migrate.md